### ISSUE TITLE
How can I receive a notice of the deposit withdraw request?

### ISSUE THREAD

**Issue by miaolz123** [FXCMAPI/ForexConnectAPI-Linux-x86_64#1]
Can I receive a notice of the deposit withdraw request in this API SDK ?

Thx~~

**Comment by FXCMAPI** [comment]
Hi,

You can use the function IO2GAccountRow.getNonTradeEquity()
This is the amount of accounting transactions that applied to the account during the current trading day,  amount is a part of the equity balance that reflects non-trading activity. It is expressed in the account currency and used for calculation of DayPL. The accounting transactions are: deposit, withdrawal and funds transfer. A trading day is from 17:00 through 17:00 EST. If there are no accounting transactions during the current trading day, the value of this field is zero.

Regards,
Daniel Halpert

**Comment by miaolz123** [comment]
Thx ~~
