### ISSUE TITLE
Do these APIs have a frequency limit on TableManager Mode ?

### ISSUE THREAD

**Issue by miaolz123** [FXCMAPI/ForexConnectAPI-Linux-x86_64#2]
I always get abort error when I run the following script frequently.

``` c++
IO2GTradesTable *tradesTable = (IO2GTradesTable *)tableManager->getTable(::Trades);
```

Maybe I use it in the wrong way, thanks anyway~

**Comment by FXCMAPI** [comment]
Hi,

I tested getTable() function with the Table Manager example program PrintTable, like this:
              for (int i=0; i < 100; i++)
                     printOrders(tableManager, sampleParams->getAccount());

I couldn’t replicate the problem you saw, maybe the abort caused by some other thing in the code.

Regards,
Daniel Halpert
